README.md
example/src/App.tsx
src/native-types.ts

This unit is as common as mmol/l and specified in https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifierbloodglucose
`HKMetadataKeyBloodGlucoseMealTime` is a key for `HKQuantityTypeIdentifier.bloodGlucose`, but `HKMetadataKeyInsulinDeliveryReason` is for `HKQuantityTypeIdentifier.insulinDelivery`.
I split the declaration and fixed examples in app and README.
Metadata keys were not working and ignored, but attempts to use methods that had required metadata fields (such as `HKQuantityTypeIdentifier.insulinDelivery`) failed.
This is because on swift side `HKMetadataKeyInsulinDeliveryReason` is a variable rather than value. I chose to change all values on typescript side because it was too finicky to create a mapping on swift side.

fix: Fix diabetes related methods

---

example/src/App.tsx
ios/ReactNativeHealthkit.swift

Hi!
First of all – thank you for this library, it's by far the most complete and straightforward HealthKit library for React Native.
I've faced the issue described here: https://github.com/Kingstinct/react-native-healthkit/issues/2
Any call to the queryQuantitySamples with the ascending parameter set to true ended up with a crash on type conversion.
I'm not very familiar with ObjC and Swift, but it seems that changing the swift method signature (making ascending argument Bool) helps.
What do you think?

Fix ascending

---

ios/ReactNativeHealthkit.swift
src/native-types.ts

Hi,
I'm in the process of migrating from the other React Native HealthKit library, and I've found that source info for HK samples is missing.
Added this to quantity, category, and workout samples. Tried to stick as close to the native types as possible.

feat: add sourceRevision info to HK samples

---

ios/ReactNativeHealthkit.swift

When updating to react native 0.64.0 pod does not compile after `RCTEventEmitter` added
```objc
- (instancetype)initWithDisabledObservation;
```
[here](https://github.com/facebook/react-native/commit/82187bfb6b54fdffc5dadaa56e8bf97d2209708a#diff-3215dd761992f420e8effa738d5ce9c03a0977b9d85b87f15529394265755912R19)
This should fix it.

Fix compilation error for react-native 0.64

---

ios/ReactNativeHealthkit.swift

An archive build fails with error "no such module combine". Combine is currently not needed and only available for [iOS 13+ ](https://developer.apple.com/documentation/combine)and can be removed.

remove combine

---

ios/ReactNativeHealthkit.m

Fix for #19 
I changed the signatures in ReactNativeHealthkit.m to match ReactNativeHealthkit.swift.
I didn't try to make them consistent since I wasn't sure about the project's naming preference.

fix: fixed mismatched objc method signatures between .m and .swift files

---

ios/ReactNativeHealthkit.m
ios/ReactNativeHealthkit.swift
src/index.ios.tsx
src/index.tsx
src/native-types.ts
src/types.ts

Hi, 
I saw that the library was missing the possibility to get locations from a workout so here is a proposed solution. 
I'm no swift expert at all so feel free to correct anything.
The new function outputs an locations as a nested array of locations
```json
[[{
"altitude": 111.11080169677734,
"horizontalAccuracy": 11.250052452087402,
"latitude": 48.79551754488684,
"longitude": 2.29879251611046,
"speed": 0.07861018180847168,
"speedAccuracy": 1.1210601329803467,
"timestamp": 1654723528.0003781,
"verticalAccuracy": 1.3213047981262207
}]]
```

feat: add support for workout locations

---

ios/ReactNativeHealthkit.swift

While testing out the library I noticed that when saving sleep the HKCategoryValue seems not to work in the case of sleep, but instead every sleep values is saved as `inBed` even if it was `asleep`. Explicitly converting the Double value to Int in `saveCategorySample` on Swift side seems to fix this.
Now I'm no Swift expert, so perhaps there is a better way to do this? I didn't also test it with all the possible  HKCategoryValues so might be that change breaks something?

fix: double conversion

---

example/src/App.tsx
ios/ReactNativeHealthkit.m
ios/ReactNativeHealthkit.swift
src/hooks/useSources.ts
src/index.ios.tsx
src/index.tsx
src/jest.setup.ts
src/native-types.ts
src/utils/querySources.ts

This PR adds new function for fetching the sources that have been used to save HealthKit samples:
- query sources with `HKCategoryTypeIdentifier` or `HKQuantityTypeIdentifier` 
- new `querySources` function for fetching sources, returns a list of source objects that contain name and bundleId of the source
- new `useSources` hook 
- new sources section in the test app with examples on fetching both  `HKCategoryTypeIdentifier` and `HKQuantityTypeIdentifier` sources

feat(hk sources): add function for fetching hk sources

---

CHANGELOG.md
README.md
app.plugin.js
example-expo/.gitignore
example-expo/app.json
example-expo/package.json
example-expo/yarn.lock
example/ios/Podfile.lock
example/src/App.tsx
ios/ReactNativeHealthkit.m
ios/ReactNativeHealthkit.swift
package.json
src/index.tsx
src/native-types.ts
src/types.ts
src/utils/deserializeCorrelation.ts
src/utils/deserializeSample.ts
src/utils/getMostRecentCategorySample.ts
src/utils/getMostRecentQuantitySample.ts
src/utils/prepareOptions.ts
src/utils/queryCategorySamples.ts
src/utils/queryQuantitySamples.ts
src/utils/serializeDate.test.ts
src/utils/serializeDate.ts

Resolves #50 
This will be a new major release since it changes slightly what is returned from the category and quantity queries, from simply an array of samples to:
```TypeScript
type ResponseType = {
samples: Sample[], // category or quantity sample
deletedSamples: DeletedSample[],
newAnchor: string
}
```
and also adds (non-breaking) the anchor parameter as an optional input to the query:
```TypeScript
const firstRes = await queryQuantitySamples(HKQuantityTypeIdentifier.stepCount, {
limit: 2,
})
const nextRes = await queryQuantitySamples(HKQuantityTypeIdentifier.stepCount, {
limit: 2,
anchor: firstRes.newAnchor,
})
```
I've given this a quick run in the example app - maybe you could have a run on it as well @ha3 and see if you have any feedback before we merge this?

Make queries anchorable

---

example/src/App.tsx
ios/ReactNativeHealthkit.m
ios/ReactNativeHealthkit.swift
src/index.ios.tsx
src/index.tsx
src/jest.setup.ts
src/native-types.ts
src/types.ts
src/utils/deserializeHeartbeatSeriesSample.ts
src/utils/queryHeartbeatSeriesSamples.ts

This PR adds functionality to query [`HKHeartbeatSeriesSample`](https://developer.apple.com/documentation/healthkit/hkheartbeatseriessample). Closes #57. 
- To obtain the raw heartbeat data it uses a [`HKHeartbeatSeriesQuery`](https://developer.apple.com/documentation/healthkit/hkheartbeatseriesquery). Another way to do it, which is probably a little more concise, would be using a [`HKHeartbeatSeriesQueryDescriptor`](https://developer.apple.com/documentation/healthkit/hkheartbeatseriesquerydescriptor). However, this requires iOS 15.4 and is not consistent with how the workout routes are currently obtained in the library ([`HKWorkoutRouteQueryDescriptor`](https://developer.apple.com/documentation/healthkit/hkworkoutroutequerydescriptor) also exists).
- Exposes …

feat: exposing HKHeartbeatSeriesQuery for Heartbeat series data

---

src/index.tsx
src/native-types.ts

Closes #61
Updates the definition of `authorizationStatusFor` to return a `HKAuthorizationStatus` (instead of a `boolean`) as per the underlying HealthKit method's [documentation](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614154-authorizationstatusfortype).

Update `authorizationStatusFor` return type

---

ios/ReactNativeHealthkit.swift

Added resolve(queryId) to the end of subscribeToObserverQuery() so that subscribeToChanges() will return an unsubscribe function

fix: subscribeToObserverQuery not resolving promise

---

ios/ReactNativeHealthkit.swift
src/native-types.ts

**Additions to queryWorkoutSamples:**
1. HKWorkoutPlan UUID for WorkoutKit in iOS 17 (https://developer.apple.com/documentation/workoutkit)
- This requires a helper function fetchWorkoutPlan to allow for the fetching of the workout.workoutPlan to be completed asynchronously and return without race conditions in queryWorkoutSamples
2. HKWorkoutEvent such as laps, pause resume - returned with their raw value, start and end timestamp
3. HKWorkoutActivity so that the activities within a custom workout created by the user can be viewed

Add more workout details to queryWorkoutSamples

---

ios/ReactNativeHealthkit.swift

Attempts to resolve https://github.com/kingstinct/react-native-healthkit/issues/78 by calling `resolve` with the newly-created dictionary object when `stats` is `nil`.
Moves from the existing `if let` to a `guard let` based on existing usages elsewhere (for example, [here](https://github.com/kingstinct/react-native-healthkit/blob/3086d95ec7fa6573767e34162f32fd3542fcf5c9/ios/ReactNativeHealthkit.swift#L848-L850)). Thus, the majority of the changes are whitespace, so would recommend viewing the diff [without whitespace](https://github.com/kingstinct/react-native-healthkit/pull/79/files?diff=unified&w=1).

Update `queryStatisticsForQuantity` to resolve when competition handler returns `nil` statistics

---

src/native-types.ts

Add latest HKWorkoutActivityType values to enum.
There doesn't seem to be an 81 (I checked twice).
Got them from [here](https://developer.apple.com/documentation/healthkit/hkworkoutactivitytype).

Update native-types.ts with latest activity types

---

ios/Serializers.swift

iOS 17 added support for the "Time in Daylight" metric that includes a metadata item measured in a new `HKUnit` `HKUnit.lux()`
This adds support for serializing this new unit to make it accessible in React Native as it does not serialize properly otherwise
Some relevant docs:
https://support.apple.com/guide/watch/see-time-in-daylight-apd3ab22534c/watchos
https://developer.apple.com/documentation/healthkit/hkunit/4126896-lux/
https://developer.apple.com/documentation/healthkit/hkmetadatakeymaximumlightintensity/

Support new lux HKUnit for iOS 17

---

src/hooks/useStatisticsForQuantity.ts

If we use the same example from the documentation we will have an permanent re-rendering per tick which causes a huge memory leak which with 2 of the same, will crash any app.
Why is this caused?
`update` function is revalue it due  useSubscribeToChanges because `update` have an setResult so the useEffect for the `update` will trigger infinite without even subscribing.
Solution: 
Removing `update` from the dependencies from useEffect will only trigger 1 time so we can have initial values, then we depends totally from useSubscribeToChanges  to trigger `update` which is the porpuse of the subscribing hook.

Fix Infinite renders/calls for using useSubscribeToChanges

---

ios/ReactNativeHealthkit.swift

Allow explicit UUIDs
https://developer.apple.com/documentation/healthkit/hkquery/1614783-predicateforobjectwithuuid
See the discussion section
closes #118

Support explicit UUIDs

---

.changeset/tall-times-ask.md
packages/react-native-healthkit/ios/WorkoutsModule.swift
packages/react-native-healthkit/src/healthkit.ts
packages/react-native-healthkit/src/specs/WorkoutsModule.nitro.ts

When creating a workout sample, return the workout proxy, so we can further interact with it; for example, to save the workout route.
Closes #199

chore: saveWorkoutSample return workout proxy

---

.changeset/moody-worlds-lead.md
apps/example/app/(tabs)/quantityTypes/index.tsx
packages/react-native-healthkit/ios/Helpers.swift
packages/react-native-healthkit/src/types/QueryOptions.ts

- Implement createMetadataPredicate in Swift with support for equalTo, notEqualTo, greaterThan, lessThan operators
- Add operator and value support to PredicateWithMetadataKey type
This is useful to i.e. filter out user entered data from the results (as shown in the example app)

feat: add metadata filtering with comparison operators

---

.changeset/soft-badgers-fry.md
packages/react-native-healthkit/ios/WorkoutsModule.swift

Fix crash when saving workout with empty quantities
```ts
const workout = await saveWorkoutSample(
WorkoutActivityType.traditionalStrengthTraining,
[],
startAt,
endAt,
{
energyBurned,
},
{},
);
```

fix: saveWorkoutSample crash with empty quantities
